[pasvault]

# Cloud Identity Portal (ID Tenant where the user is managed)
idtenanturl = "https://IDENTITY_TENANT_ID.id.cyberark.cloud"

# User must be able to create PAS Vault account
user = 'MYUSER' 
pass = 'MYPASSWORD'

# Privilege Cloud (Where the Vault-safe is located)
pcloudurl = "https://cybr-secrets.privilegecloud.cyberark.cloud"
safename = "safe1"
